
package com.tekvizion.tekeye.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutomationServiceWsImpl", targetNamespace = "http://ws.tekeye.tekvizion.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutomationServiceWsImpl {


    /**
     * 
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestPlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatableTestplans", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestplans")
    @ResponseWrapper(localName = "listAutomatableTestplansResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestplansResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestplansRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestplansResponse")
    public List<WsTestPlan> listAutomatableTestplans();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestCase>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatedTestCases", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatedTestCases")
    @ResponseWrapper(localName = "listAutomatedTestCasesResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatedTestCasesResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatedTestCasesRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatedTestCasesResponse")
    public List<WsTestCase> listAutomatedTestCases(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsAutomationScript>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllTestCaseAutomationScripts", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllTestCaseAutomationScripts")
    @ResponseWrapper(localName = "listAllTestCaseAutomationScriptsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllTestCaseAutomationScriptsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllTestCaseAutomationScriptsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllTestCaseAutomationScriptsResponse")
    public List<WsAutomationScript> listAllTestCaseAutomationScripts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsAutomationScript
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAutomationScriptById", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetAutomationScriptById")
    @ResponseWrapper(localName = "getAutomationScriptByIdResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetAutomationScriptByIdResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getAutomationScriptByIdRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getAutomationScriptByIdResponse")
    public WsAutomationScript getAutomationScriptById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsAutomationScript
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestCaseAutomationScriptByName", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestCaseAutomationScriptByName")
    @ResponseWrapper(localName = "getTestCaseAutomationScriptByNameResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestCaseAutomationScriptByNameResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestCaseAutomationScriptByNameRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestCaseAutomationScriptByNameResponse")
    public WsAutomationScript getTestCaseAutomationScriptByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsAutomationScript>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomationScriptsByTestplan", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomationScriptsByTestplan")
    @ResponseWrapper(localName = "listAutomationScriptsByTestplanResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomationScriptsByTestplanResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomationScriptsByTestplanRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomationScriptsByTestplanResponse")
    public List<WsAutomationScript> listAutomationScriptsByTestplan(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsAutomationScript>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTestCaseAutomationScriptsByExtension", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListTestCaseAutomationScriptsByExtension")
    @ResponseWrapper(localName = "listTestCaseAutomationScriptsByExtensionResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListTestCaseAutomationScriptsByExtensionResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listTestCaseAutomationScriptsByExtensionRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listTestCaseAutomationScriptsByExtensionResponse")
    public List<WsAutomationScript> listTestCaseAutomationScriptsByExtension(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastModifiedDateOfTestPlan", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetLastModifiedDateOfTestPlan")
    @ResponseWrapper(localName = "getLastModifiedDateOfTestPlanResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetLastModifiedDateOfTestPlanResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getLastModifiedDateOfTestPlanRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getLastModifiedDateOfTestPlanResponse")
    public XMLGregorianCalendar getLastModifiedDateOfTestPlan(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastModifiedDateOfTestCase", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetLastModifiedDateOfTestCase")
    @ResponseWrapper(localName = "getLastModifiedDateOfTestCaseResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetLastModifiedDateOfTestCaseResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getLastModifiedDateOfTestCaseRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getLastModifiedDateOfTestCaseResponse")
    public XMLGregorianCalendar getLastModifiedDateOfTestCase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestCase>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllTestCases", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllTestCases")
    @ResponseWrapper(localName = "listAllTestCasesResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllTestCasesResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllTestCasesRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllTestCasesResponse")
    public List<WsTestCase> listAllTestCases(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadMultipleAutomationScripts", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.UploadMultipleAutomationScripts")
    @ResponseWrapper(localName = "uploadMultipleAutomationScriptsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.UploadMultipleAutomationScriptsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/uploadMultipleAutomationScriptsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/uploadMultipleAutomationScriptsResponse")
    public WsErrorCodes uploadMultipleAutomationScripts(
        @WebParam(name = "arg0", targetNamespace = "")
        List<WsAutomationScript> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadTestcaseAutomationScript", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.UploadTestcaseAutomationScript")
    @ResponseWrapper(localName = "uploadTestcaseAutomationScriptResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.UploadTestcaseAutomationScriptResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/uploadTestcaseAutomationScriptRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/uploadTestcaseAutomationScriptResponse")
    public WsErrorCodes uploadTestcaseAutomationScript(
        @WebParam(name = "arg0", targetNamespace = "")
        WsAutomationScript arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAutomationScriptById", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAutomationScriptById")
    @ResponseWrapper(localName = "deleteAutomationScriptByIdResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAutomationScriptByIdResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAutomationScriptByIdRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAutomationScriptByIdResponse")
    public WsErrorCodes deleteAutomationScriptById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTestCaseAutomationScriptByName", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteTestCaseAutomationScriptByName")
    @ResponseWrapper(localName = "deleteTestCaseAutomationScriptByNameResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteTestCaseAutomationScriptByNameResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteTestCaseAutomationScriptByNameRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteTestCaseAutomationScriptByNameResponse")
    public WsErrorCodes deleteTestCaseAutomationScriptByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAllTestCaseAutomationScripts", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAllTestCaseAutomationScripts")
    @ResponseWrapper(localName = "deleteAllTestCaseAutomationScriptsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAllTestCaseAutomationScriptsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAllTestCaseAutomationScriptsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAllTestCaseAutomationScriptsResponse")
    public WsErrorCodes deleteAllTestCaseAutomationScripts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsErrorCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAllTestCaseAutomationScriptsByExtension", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAllTestCaseAutomationScriptsByExtension")
    @ResponseWrapper(localName = "deleteAllTestCaseAutomationScriptsByExtensionResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.DeleteAllTestCaseAutomationScriptsByExtensionResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAllTestCaseAutomationScriptsByExtensionRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/deleteAllTestCaseAutomationScriptsByExtensionResponse")
    public WsErrorCodes deleteAllTestCaseAutomationScriptsByExtension(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsTestPlan
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestPlanDetails", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestPlanDetails")
    @ResponseWrapper(localName = "getTestPlanDetailsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestPlanDetailsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestPlanDetailsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestPlanDetailsResponse")
    public WsTestPlan getTestPlanDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsTestCase
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestCaseDetails", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestCaseDetails")
    @ResponseWrapper(localName = "getTestCaseDetailsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetTestCaseDetailsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestCaseDetailsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getTestCaseDetailsResponse")
    public WsTestCase getTestCaseDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestPlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllAutomatableStandardTestPlans", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllAutomatableStandardTestPlans")
    @ResponseWrapper(localName = "listAllAutomatableStandardTestPlansResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAllAutomatableStandardTestPlansResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllAutomatableStandardTestPlansRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAllAutomatableStandardTestPlansResponse")
    public List<WsTestPlan> listAllAutomatableStandardTestPlans();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestPlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatableStandardTestPlansByStatus", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableStandardTestPlansByStatus")
    @ResponseWrapper(localName = "listAutomatableStandardTestPlansByStatusResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableStandardTestPlansByStatusResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableStandardTestPlansByStatusRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableStandardTestPlansByStatusResponse")
    public List<WsTestPlan> listAutomatableStandardTestPlansByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestPlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatableTestPlansByCustomerAndStatus", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestPlansByCustomerAndStatus")
    @ResponseWrapper(localName = "listAutomatableTestPlansByCustomerAndStatusResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestPlansByCustomerAndStatusResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestPlansByCustomerAndStatusRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestPlansByCustomerAndStatusResponse")
    public List<WsTestPlan> listAutomatableTestPlansByCustomerAndStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestCase>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatedTestCasesByStatus", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatedTestCasesByStatus")
    @ResponseWrapper(localName = "listAutomatedTestCasesByStatusResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatedTestCasesByStatusResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatedTestCasesByStatusRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatedTestCasesByStatusResponse")
    public List<WsTestCase> listAutomatedTestCasesByStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tekvizion.tekeye.ws.WsConfiguration
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConfigurationDetails", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetConfigurationDetails")
    @ResponseWrapper(localName = "getConfigurationDetailsResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetConfigurationDetailsResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getConfigurationDetailsRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getConfigurationDetailsResponse")
    public WsConfiguration getConfigurationDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsConfiguration>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConfigurationsOfTestPlan", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetConfigurationsOfTestPlan")
    @ResponseWrapper(localName = "getConfigurationsOfTestPlanResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.GetConfigurationsOfTestPlanResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getConfigurationsOfTestPlanRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/getConfigurationsOfTestPlanResponse")
    public List<WsConfiguration> getConfigurationsOfTestPlan(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tekvizion.tekeye.ws.WsTestCase>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAutomatableTestcaseListByTestPlan", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestcaseListByTestPlan")
    @ResponseWrapper(localName = "listAutomatableTestcaseListByTestPlanResponse", targetNamespace = "http://ws.tekeye.tekvizion.com/", className = "com.tekvizion.tekeye.ws.ListAutomatableTestcaseListByTestPlanResponse")
    @Action(input = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestcaseListByTestPlanRequest", output = "http://ws.tekeye.tekvizion.com/AutomationServiceWsImpl/listAutomatableTestcaseListByTestPlanResponse")
    public List<WsTestCase> listAutomatableTestcaseListByTestPlan(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
