
package com.tekvizion.tekeye.ws;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutomationServiceWsImplService", targetNamespace = "http://ws.tekeye.tekvizion.com/", wsdlLocation = "http://10.89.1.34:8090/wsAutomation?wsdl")
public class AutomationServiceWsImplService
    extends Service
{

    private final static URL AUTOMATIONSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOMATIONSERVICEWSIMPLSERVICE_EXCEPTION;
    private final static QName AUTOMATIONSERVICEWSIMPLSERVICE_QNAME = new QName("http://ws.tekeye.tekvizion.com/", "AutomationServiceWsImplService");
    
    private static Properties properties = null;
    
    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL("http://10.89.1.34:8090/wsAutomation?wsdl");
        	
        	properties = new Properties();
        	
        	File f = new File(""+System.getProperty("catalina.base")+"/AutomationEditor.properties");
        	if(f.exists()){
        		InputStream input = new FileInputStream(System.getProperty("catalina.base")+"/AutomationEditor.properties");
        		properties.load(input);
        		if(properties.containsKey("app.settings.tops.url")){
    				url = new URL(properties.getProperty("app.settings.tops.url"));
    			}
        	}else{
        		properties.load(Thread.currentThread().getContextClassLoader().getResourceAsStream("AutomationEditor.properties"));
    			if(properties.containsKey("app.settings.tops.url")){
    				url = new URL(properties.getProperty("app.settings.tops.url"));
    			}
        	}
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        AUTOMATIONSERVICEWSIMPLSERVICE_WSDL_LOCATION = url;
        AUTOMATIONSERVICEWSIMPLSERVICE_EXCEPTION = e;
    }

    public AutomationServiceWsImplService() {
        super(__getWsdlLocation(), AUTOMATIONSERVICEWSIMPLSERVICE_QNAME);
    }

    public AutomationServiceWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOMATIONSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public AutomationServiceWsImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTOMATIONSERVICEWSIMPLSERVICE_QNAME);
    }

    public AutomationServiceWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOMATIONSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public AutomationServiceWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomationServiceWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutomationServiceWsImpl
     */
    @WebEndpoint(name = "AutomationServiceWsImplPort")
    public AutomationServiceWsImpl getAutomationServiceWsImplPort() {
        return super.getPort(new QName("http://ws.tekeye.tekvizion.com/", "AutomationServiceWsImplPort"), AutomationServiceWsImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomationServiceWsImpl
     */
    @WebEndpoint(name = "AutomationServiceWsImplPort")
    public AutomationServiceWsImpl getAutomationServiceWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.tekeye.tekvizion.com/", "AutomationServiceWsImplPort"), AutomationServiceWsImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOMATIONSERVICEWSIMPLSERVICE_EXCEPTION!= null) {
            throw AUTOMATIONSERVICEWSIMPLSERVICE_EXCEPTION;
        }
        return AUTOMATIONSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
